version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password_db
    ports:
      - "3307:3306"  # Modifica la porta se 3306 è già in uso
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8082:80"  # Modifica la porta se 8080/8081 sono in uso
    depends_on:
      - db

  app:
    build:
      context: .
    container_name: password_generator_app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=password_db
    depends_on:
      - db
    ports:
      - "5000:5000"  # Espone l’API Flask

volumes:
  mysql_data:
